# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Calculate_pb2 as Calculate__pb2


class CalculatingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.calculate = channel.unary_unary(
                '/CalculatingService/calculate',
                request_serializer=Calculate__pb2.Request.SerializeToString,
                response_deserializer=Calculate__pb2.Response.FromString,
                )
        self.test = channel.unary_unary(
                '/CalculatingService/test',
                request_serializer=Calculate__pb2.Test.SerializeToString,
                response_deserializer=Calculate__pb2.Test.FromString,
                )


class CalculatingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def calculate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def test(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'calculate': grpc.unary_unary_rpc_method_handler(
                    servicer.calculate,
                    request_deserializer=Calculate__pb2.Request.FromString,
                    response_serializer=Calculate__pb2.Response.SerializeToString,
            ),
            'test': grpc.unary_unary_rpc_method_handler(
                    servicer.test,
                    request_deserializer=Calculate__pb2.Test.FromString,
                    response_serializer=Calculate__pb2.Test.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CalculatingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CalculatingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def calculate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CalculatingService/calculate',
            Calculate__pb2.Request.SerializeToString,
            Calculate__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CalculatingService/test',
            Calculate__pb2.Test.SerializeToString,
            Calculate__pb2.Test.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
