production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: "smtp.gmail.com"
      port: '587'
      domain: "redmine.freydin.space"
      authentication: :plain
      user_name: "www.carat.ru@gmail.com"
      password: "zsvurwyeqmpyrgzt"